# Generated by Django 5.1.3 on 2024-11-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
