# Generated by Django 5.1.3 on 2024-11-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='headers/'),
        ),
    ]
