# Generated by Django 5.1.3 on 2024-12-16 11:11

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='review',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Review'),
        ),
    ]
