# Generated by Django 5.1.3 on 2024-12-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='nick',
            field=models.CharField(default='Anónimo', max_length=50),
            preserve_default=False,
        ),
    ]
