# Generated by Django 5.1.3 on 2025-01-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_season_episode_series_season_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='drive_url',
        ),
        migrations.AddField(
            model_name='episode',
            name='drive_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
