# Generated by Django 5.1.3 on 2025-01-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_series_drive_url_episode_drive_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
