# Generated by Django 5.1.3 on 2025-02-17 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_episode_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='favorite_by_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='watchlist_by_users',
            field=models.ManyToManyField(blank=True, related_name='watchlist_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, choices=[(0.5, '0.5 ⭐'), (1.0, '1.0 ⭐'), (1.5, '1.5 ⭐'), (2.0, '2.0 ⭐'), (2.5, '2.5 ⭐'), (3.0, '3.0 ⭐'), (3.5, '3.5 ⭐'), (4.0, '4.0 ⭐'), (4.5, '4.5 ⭐'), (5.0, '5.0 ⭐')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('movie', 'user')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='user_ratings',
            field=models.ManyToManyField(blank=True, related_name='rated_movies', through='movies.MovieRating', to=settings.AUTH_USER_MODEL),
        ),
    ]
