# Generated by Django 5.1.3 on 2025-02-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_movie_favorite_by_users_movie_watchlist_by_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collection_covers/')),
                ('movies', models.ManyToManyField(blank=True, related_name='collections', to='movies.movie')),
            ],
        ),
    ]
